# Numpy
Numpy의 소개
NumPy(Numerical Python)는 파이썬에서 과학적 계산을 위한 핵심 라이브러리이다.
NumPy는 다차원 배열 객체와 배열과 함께 작동하는 도구들을 제공한다.
하지만 NumPy 자체로는 고수준의 데이터 분석 기능을 제공하지 않기 때문에
NumPy 배열과 배열 기반 컴퓨팅의 이해를 통해 pandas와 같은 도구를 좀 더 효율적으로 사용하는 것이 필요하다.

### ndarray 생성

array 함수를 사용하여 배열 생성하기

In [2]:
import numpy as np

In [4]:
# ndarray를 생성
arr=np.array([1,2,3,4])

In [5]:
print(arr)

[1 2 3 4]


In [6]:
type(arr)

numpy.ndarray

In [7]:
a=[1,2,3,4]

In [8]:
type(a)

list

In [9]:
np.zeros((3,3)) #미리 0으로 초기화를 한다(다른 값이 들어있기 전에 그냥 초기화)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,3)) #1뒤에 .이 붙어 있는 이유는 실수이기 때문이다

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
type(np)

module

In [12]:
np.empty((4,4)) #가비지 값들

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34613185e-307],
       [6.23058028e-307, 2.22522597e-306, 1.33511969e-306,
        1.37962320e-306],
       [9.34604358e-307, 9.79101082e-307, 1.78020576e-306,
        1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306, 8.06632139e-308,
        1.60221208e-306]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## ndarray 배열의 모양, 차수, 데이터 타입 확인하기

In [24]:
arr=np.array([[1,2,3],[4,5,6]])

In [25]:
arr.shape

(2, 3)

In [26]:
arr.ndim

2

In [27]:
arr.dtype

dtype('int32')

In [28]:
arr_float=arr.astype(np.float64)

In [29]:
print(arr_float)

[[1. 2. 3.]
 [4. 5. 6.]]


In [30]:
arr_float.dtype

dtype('float64')

In [31]:
arr.dtype

dtype('int32')

In [32]:
arr1=np.array([[1,2],[3,4]])

In [33]:
arr2=np.array([[5,6],[7,8]])

In [34]:
arr3=arr1+arr2

In [35]:
print(arr3) #같은 위치에 있는 요소들끼리 더해져서 나옴

[[ 6  8]
 [10 12]]


In [36]:
arr3=arr1*arr2

In [37]:
print(arr3)

[[ 5 12]
 [21 32]]


In [38]:
arr4=np.add(arr1,arr2)
print(arr4)

[[ 6  8]
 [10 12]]


In [39]:
arr3=np.multiply(arr1,arr2)
print(arr3)

[[ 5 12]
 [21 32]]


Numpy 배열의 연산은 연산자 (+,-,*,/)나 함수(add, subtract, multiply, divide)로 가능하다.

### ndarray 배열 슬라이싱 하기
ndarray 배열 슬라이싱하기

In [41]:
#배열 슬라이싱
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
arr_1=arr[:2,1:3]

In [43]:
print(arr_1)

[[2 3]
 [5 6]]


In [47]:
arr.shape

(3, 3)

In [52]:
arr_int=np.arange(10)
print(arr_int[:])

[0 1 2 3 4 5 6 7 8 9]


In [53]:
print(arr[0,2])

3


In [56]:
arr=np.array([[1,2,3],[4,5,6]])

In [58]:
idx=arr>3
print(idx)

[[False False False]
 [ True  True  True]]


In [59]:
print(arr[idx]) #idx배열에서 true인 요소들만 추출한다

[4 5 6]


In [64]:
redwine=np.loadtxt(fname='winequality-red.csv',
           delimiter=';', # ";"라는 구분자로 나누어져 있음
          skiprows=1) #1행까지 스킵

print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [66]:
redwine.shape #전체 데이터는 1599개이고, column은 12개다

(1599, 12)

In [67]:
type(redwine)

numpy.ndarray

In [68]:
print(redwine.sum())

152084.78194


In [69]:
print(redwine.mean(axis=0)) #axis는 축이라는 뜻이다. 기본(0)은 가로축!

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [70]:
print(redwine[:,0].mean()) #전부다, 첫번째 배열만

8.31963727329581
